name: CI
on:
  - push
  - pull_request
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Fmt
        if: always() && steps.install_rust.outcome == 'success'
        run: cargo fmt -- --check
  release:
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: ci
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        include:
          - os: windows-latest
            filename: ./target/release/rdr2-screenshots.exe#Windows
          - os: ubuntu-latest
            filename: ./target/release/rdr2-screenshots#Linux
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --locked
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${GITHUB_REF#refs/tags/} ${{ matrix.filename }}
